---
# Site settings
title: Joseph Rex's blog - Exploring Software, Food recipes, and Design
email: joseph\*\*at\*\*strichio
description: > # this means to ignore newlines until "baseurl:"
  Ramblings on design, code, fitness and food by Joseph Rex
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://josephrex.me" # the base hostname & protocol for your site
twitter_username: josephrexme
github_username:  bl4ckdu5t

# Build settings
markdown: kramdown

assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/posts
css_compressor:	sass
js_compressor: 	uglifier
cache: 		true
exclude:
  - gulpfile.js
  - package.json
  - node_modules
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .gitignore
gems:
  - jekyll-sitemap

timezone: America/Chicago
excerpt_separator: <!--more-->
paginate: 8
incremental: true # Incremental regeneration

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
