---
# Site settings
title: Joseph Rex
email: joerex@ostrich-dev.com
description: > # this means to ignore newlines until "baseurl:"
  Exploring Software and Applications
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://josephrex.me" # the base hostname & protocol for your site
twitter_username: joerex101
github_username:  bl4ckdu5t

# Build settings
markdown: kramdown

assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/posts
css_compressor:	sass
js_compressor: 	uglifier
cache: 		true
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .gitignore
gems:
  - jekyll-sitemap

excerpt_separator: <!--more-->
