# Site settings
baseurl: https://www.josephrex.me/
themesDir: ./themes/
languageCode: en-us
metaDataFormat: yaml
title: Joseph Rex's website - Portfolio, Resume, Designs, and Publications
theme: connoisseur
# Enter your tracking code to enable Google Analytics
googleAnalytics: UA-56161232-2
# Disable comments by leaving disqusShortname empty
disqusShortname: josephrexme
disablePathToLower: true
pygmentsstyle: native
RSSLink: feed.xml
paginate: 4

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed

params:
  name: Joseph Rex
  description: Articles, Designs, Animations, and Projects by Joseph Rex
  bio: a creative technologist and UI enthusiast
  secondaryBio: CSS, JavaScript, Ruby, 3D, XR, Animation, Design, and Life
  email: joseph\*\*at\*\*scade.xyz
  profile: https://josephrex.me
  enableRSS: true
  themeBuilder: true
  favicon: favicon.png # A file located in the static directory
  logo: logo.png # Also located in static directory for logo
  banner: https://res.cloudinary.com/strich/image/upload/v1614466088/JR_logo_-_alpha_rsnlqi.png # Used for opengraph
  themeColor: #b30950
  ckformid: 1526099

social:
  facebook: https://facebook.com/josephrexme
  twitter: https://twitter.com/josephrexme
  github: https://github.com/josephrexme
  codepen: https://codepen.io/josephrexme
  dribbble: https://dribbble.com/josephrexme
  behance: https://behance.net/josephrexme
  stackoverflow: http://stackoverflow.com/users/2649933/joseph-rex?tab=profile
  pinterest: https://pinterest.com/josephrexme
  instagram: https://instagram.com/josephrexme
  linkedin: https://www.linkedin.com/in/josephrexme
  keybase: https://keybase.io/josephrexme
  patreon: https://patreon.com/josephrexme
