# Site settings
baseurl: https://josephrex.me/
themesDir: ./themes/
languageCode: en-us
metaDataFormat: yaml
title: Joseph Rex's blog - Exploring Software, Food recipes, and Design
theme: connoisseur
# Enter your tracking code to enable Google Analytics
googleAnalytics: UA-56161232-2
# Disable comments by leaving disqusShortname empty
disqusShortname: josephrexme
disablePathToLower: true
pygmentsstyle: paraiso-dark
RSSLink: feed.xml
paginate: 4

outputs:
  home:
    - HTML
    - RSS

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed

params:
  name: Joseph Rex
  description: Ramblings on design, code, fitness and food by Joseph Rex
  bio: Design, Code, Fitness and Food
  email: joseph\*\*at\*\*strichio
  profile: https://josephrex.me/about-me
  enableRSS: true
  themeBuilder: true
  favicon: favicon.png # A file located in the static directory
  logo: logo.png # Also located in static directory for logo
  banner: https://res.cloudinary.com/strich/image/upload/v1501762952/banner_zblgpl.png # Used for opengraph
  themeColor: #b30950

social:
  facebook: https://facebook.com/josephrexme
  twitter : https://twitter.com/josephrexme
  github  : https://github.com/josephrexme
  codepen: https://codepen.io/josephrexme
  dribbble : https://dribbble.com/josephrexme
  behance: https://behance.net/josephrexme
  stackoverflow: http://stackoverflow.com/users/2649933/joseph-rex?tab=profile
  pinterest: https://pinterest.com/josephrexme
  instagram: https://instagram.com/josephrexme
  linkedin: https://www.linkedin.com/in/josephrexme
